DOUBLED_INTERPUNCTION_PENALTY = 0.1
TOO_MANY_CAPS_PENALTY = 0.015
CAP_WORDS_SMALL_PENALTY = 0.15
CAP_WORDS_BIG_PENALTY = 0.25
MISSING_CAPITALISATION_PENALTY =  0.15
MISSING_SPACE_PENALTY = 0.05
WEIRD_TIME_PENALTY = 0.1
NON_ASCII_PENALTY = 0.2
SENDER_NON_ASCII_PENALTY = 0.35
SENDER_NUMBER_PENALTY = 0.1 # per number


SEXY_SENDER_PENALTY = 1
SEXY_LINK_PENALTY = 0.4
MONEY_SENDER_PENALTY = 0.2
MONEY_LINK_PENALTY = 0.1

DICT_SEXY = 0.2 #vadi i jen jedno
DICT_MONEY = 0.05  # 3 a pak dalsi 0.05 each
DICT_COUNTRIES = 0.1 #za jakykoliv
DICT_URGENT = 0.05 # jedno ok, 2 a vic uz 0.05 each

